<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Table-of-Contents" data-toc-modified-id="Table-of-Contents-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Table of Contents</a></span></li><li><span><a href="#Array-Creation-and-their-Properties" data-toc-modified-id="Array-Creation-and-their-Properties-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Array Creation and their Properties</a></span><ul class="toc-item"><li><span><a href="#Create-Arrays-from-Iterables" data-toc-modified-id="Create-Arrays-from-Iterables-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Create Arrays from Iterables</a></span></li><li><span><a href="#Creating-Empty-Arrays" data-toc-modified-id="Creating-Empty-Arrays-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Creating Empty Arrays</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#set-the-dimensions-and-their-size-with-shape" data-toc-modified-id="set-the-dimensions-and-their-size-with-shape-2.2.0.1"><span class="toc-item-num">2.2.0.1&nbsp;&nbsp;</span>set the dimensions and their size with <code>shape</code></a></span></li></ul></li></ul></li><li><span><a href="#Creating-Non-Empty-Arrays" data-toc-modified-id="Creating-Non-Empty-Arrays-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Creating Non-Empty Arrays</a></span></li><li><span><a href="#Common-Attributes-of-Arrays" data-toc-modified-id="Common-Attributes-of-Arrays-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Common Attributes of Arrays</a></span></li><li><span><a href="#Flags" data-toc-modified-id="Flags-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Flags</a></span><ul class="toc-item"><li><span><a href="#Information-about-memory-usage" data-toc-modified-id="Information-about-memory-usage-2.5.1"><span class="toc-item-num">2.5.1&nbsp;&nbsp;</span>Information about memory usage</a></span></li></ul></li></ul></li><li><span><a href="#Exercises:" data-toc-modified-id="Exercises:-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Exercises:</a></span></li></ul></div>

# Array Creation and their Properties

In [1]:
import numpy as np

## Create Arrays from Iterables

In [6]:
my_list = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
data = np.array(my_list)

data.dtype

dtype('int64')

In [ ]:
# Making sure you have an array:

my_big_list = range(100000)
big_data = np.array(my_big_list)

print("create ndarray from list")
%timeit -n 10 np.asarray(my_big_list)

print("\ncreate ndarray from ndarray")
%timeit -n 10 np.asarray(big_data)

## Creating Empty Arrays
#### set the dimensions and their size with `shape` 

np.empty creates a new array, but reuses whatever is in memory

In [7]:
np.empty(shape=(2, 3))  # 2 rows, 3 columns

array([[2.0e+000, 2.0e+000, 8.4e-323],
       [0.0e+000, 0.0e+000, 0.0e+000]])

np.zero zeros out the memory for you

In [8]:
np.zeros(shape=(2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(shape=(2, 3)) - 42  # numpy magic!!! More in chapter "broadcasting"

array([[-41., -41., -41.],
       [-41., -41., -41.]])

## Creating Non-Empty Arrays

Example: Range from 0 to 2$\pi$ in 10 steps

In [14]:
# using arange (analog to range, but supports different data types)
np.arange(0, 2 * np.pi , 2 * np.pi / 9.)

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361])

In [15]:
# easier:
np.linspace(0, 2 * np.pi, num=10, endpoint=True)

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

Example: 2 x 5 array with random numbers from the interval [0, 1]

In [ ]:
np.random.rand(2, 5)

Example: 3 x 3 array with "1"s on the main diagonal

In [ ]:
np.identity(3)

## Common Attributes of Arrays

In [ ]:
data = np.identity(5)
data

In [ ]:
# dimension of the array
data.ndim

In [ ]:
# shape: Number of elements in each dimension
data.shape

In [ ]:
# number of elements
data.size

In [ ]:
# type of the elements
data.dtype

In [ ]:
# number of bits to the next entry in each dimension
data.strides

## Flags
### Information about memory usage

In [ ]:
data.flags

last three can be set by the user

---

# Exercises:

<div class="alert alert-success">
create an empty array arr1 going from 100 to 0 in steps of 20 (`[100, 80, ..., 0]`) and an array arr2 with 100 elements from 0.07 to 42, excluding the endpoint
<li>  which datatypes are used? </li>
<li> how can you set the datatype? </li>
    </div>

In [ ]:
arr1 = np.arange(100, -1, -20)
print(arr1, arr1.dtype)

arr2 = np.linspace(0.07, 42, num=100, endpoint=False)
print(arr2, arr2.dtype)

arr1 = np.arange(100, -1, -20, dtype=np.float32)
print(arr1, arr1.dtype)

<div class="alert alert-success">
Create three arrays with a shape of (10, 20, 30) filled with, "0", with "1", and "47.11"
<li> which method is fastest? (and why?)</li>
<li> what does `len(a)` return? </li>
</div>

In [ ]:
print("empty:")
%timeit -n 100 np.empty(shape=(10, 20, 30))

print("\nzeros:")
%timeit -n 100 np.zeros(shape=(10, 20, 30))

print("\nones:")
%timeit -n 100 np.ones(shape=(10, 20, 30))

print("\n47.11:")
%timeit -n 100 np.ones(shape=(10, 20, 30)) * 47.11

empty = np.empty(shape=(10, 20, 30))
print("shape: {}, len: {}".format(empty.shape, len(empty)))

<div class="alert alert-success">
Create a 5 x 5 array with "1" on the secondary-diagonal (hint: np.eye)
</div>

In [ ]:
np.eye(5, 5, 1)

<div class="alert alert-success">
What does array.astype do?
</div>

In [ ]:
help(empty.astype)