<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Table-of-Contents" data-toc-modified-id="Table-of-Contents-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Table of Contents</a></span></li><li><span><a href="#Indexing-and-Slicing" data-toc-modified-id="Indexing-and-Slicing-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Indexing and Slicing</a></span><ul class="toc-item"><li><span><a href="#Simple-Indexing" data-toc-modified-id="Simple-Indexing-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Simple Indexing</a></span></li><li><span><a href="#Using-slices" data-toc-modified-id="Using-slices-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Using <code>slices</code></a></span></li><li><span><a href="#Advanced-slicing" data-toc-modified-id="Advanced-slicing-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Advanced slicing</a></span></li><li><span><a href="#Indexing-via-lists/arrays" data-toc-modified-id="Indexing-via-lists/arrays-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Indexing via lists/arrays</a></span></li></ul></li><li><span><a href="#Exercises:" data-toc-modified-id="Exercises:-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Exercises:</a></span></li></ul></div>

# Indexing and Slicing
## Simple Indexing

![axis](files/axis.png)



<div class="alert alert">
**Warning for FORTRAN/MATLAB-Users: the index is 0-based!**
</div>


In [4]:
import numpy as np

data = np.arange(1, 28).reshape(3, 3, 3)

green = data[1, 2, 2]  # not the same as data[1][2][2]
print(green)

# Alternative:
green = data[-2, -1, -1]    # Indexing from the end

# Assignment:
data[0, 1, 2] = 4711

18


In [6]:




data[1, 2]

array([16, 17, 18])

## Using `slices`

![slice_1](files/slice_1.png "slice_1")
![slice_2](files/slice_2.png "slice_2")
![slice_3](files/slice_3.png "slice_3")
![slice_5](files/slice_5.png "slice_5")

In [7]:
data = np.arange(1, 10).reshape(3, 3)

# Select the second row
data[1, :]

array([4, 5, 6])

In [8]:
# Selecting every second row
data[::2]

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
# Selecting everything until the second row and column
data[:2, :2]

In [ ]:
# Careful!!! data[:2][:2] != data[:2, :2] !!!
data[:2][:2]

In [9]:
# assignment via "fancy" indexing:
data[:, 1:] = 99
data

array([[ 1, 99, 99],
       [ 4, 99, 99],
       [ 7, 99, 99]])

## Advanced slicing
![slice_6](files/slice_6.png "slice_6")

In [ ]:
data = np.array([[1, 2, 5], [5, 4, 7], [3, 9, 2]])

In [ ]:
# Choosing all entries > 4
data[data > 4]

In [ ]:
# What's happening here?
data > 4

In [ ]:
# Getting all indices where "data > 4" (np.where gets the indices of all True elements): 
np.where(data > 4)

In [ ]:
# Getting the diagonal elements
data.diagonal()

## Indexing via lists/arrays

In [11]:
data = (np.ones(shape=(4, 7)) * np.arange(0, 7)).T
print("data:\n{}\n".format(data))

selection = data[[True, False, True, True, False, False, False]]
print("selection:\n{}\n".format(selection))

data:
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]]

selection:
[[0. 0. 0. 0.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]



# Exercises:

<div class="alert alert-success">
<li>Create an 8 x 8 check board with 1s and 0s</li>

</div>

In [ ]:
chess = np.zeros(shape=(8, 8), dtype=int)
chess[1::2, ::2] = 1
chess[::2, 1::2] = 1
print(chess)

<div class="alert alert-success">
<li> Choose all colored elements </li>
</div>
![slice_7](files/slice_7.png "slice_7")  

In [ ]:
data = np.arange(1, 26).reshape(5, 5)
data

In [ ]:
yellow = np.diag(data)
print("yellow:\n{}".format(yellow))

green = data[1::3]
print("\ngreen:\n{}".format(green))

blue = data[2:4, 1:3]
print("\nblue:\n{}".format(blue))

<div class="alert alert-success">
<li> assign all yellow elements to 42 (indices\_from_...)</li></div>

In [ ]:
data[np.diag_indices_from(data)] = 42
data

<div class="alert alert-success">
<li>Select all elements which are odd and dividable by seven</li>
</div>

In [ ]:
arr = np.arange(100)

<div class="alert alert-success">
<li>Select all elements from arr1 where the entries in arr2 are larger than 2, with arr1 an arr2 arrays with random numbers between 0 and 10</li>
</div>

In [ ]:
arr1 = np.random.randint(0, 10, 10)  
arr2 = np.random.randint(0, 10, 10)

print("arr1:\n  {}\narr2:\n  {}".format(arr1, arr2))

In [ ]:
arr1[arr2 > 2]

<div class="alert alert-success">
<li>Create an 8 x 8 int)array with 1 on the diagonal, 3 on the tertiary diagonal and 9 in the lower triangle (hint: use np.diag_indices_from, np.eye and np.trial)</li>
</div>

In [ ]:
data = np.zeros((8, 8), dtype=int)

data[np.diag_indices_from(data)] = 1
data

In [ ]:
data[np.tril_indices_from(data, -1)] = 9
data