<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Table-of-Contents" data-toc-modified-id="Table-of-Contents-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Table of Contents</a></span></li><li><span><a href="#04-Basic-Array-Operations" data-toc-modified-id="04-Basic-Array-Operations-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>04 Basic Array Operations</a></span><ul class="toc-item"><li><span><a href="#Array-and-Scalars" data-toc-modified-id="Array-and-Scalars-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Array and Scalars</a></span></li><li><span><a href="#Array-and-Arrays" data-toc-modified-id="Array-and-Arrays-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Array and Arrays</a></span></li><li><span><a href="#Multi-Dimensional" data-toc-modified-id="Multi-Dimensional-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Multi-Dimensional</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#even-NumPy-can't-do-wonders" data-toc-modified-id="even-NumPy-can't-do-wonders-2.3.0.1"><span class="toc-item-num">2.3.0.1&nbsp;&nbsp;</span>even NumPy can't do wonders</a></span></li></ul></li></ul></li><li><span><a href="#Mathematical-Funtions" data-toc-modified-id="Mathematical-Funtions-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Mathematical Funtions</a></span></li><li><span><a href="#Universal-Functions" data-toc-modified-id="Universal-Functions-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Universal Functions</a></span></li></ul></li><li><span><a href="#More-Examples" data-toc-modified-id="More-Examples-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>More Examples</a></span><ul class="toc-item"><li><span><a href="#Transpose" data-toc-modified-id="Transpose-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Transpose</a></span></li><li><span><a href="#Test-for-Array-properties" data-toc-modified-id="Test-for-Array-properties-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Test for Array properties</a></span><ul class="toc-item"><li><span><a href="#Test-on-Equality" data-toc-modified-id="Test-on-Equality-3.2.1"><span class="toc-item-num">3.2.1&nbsp;&nbsp;</span>Test on Equality</a></span></li></ul></li></ul></li><li><span><a href="#Exercises:" data-toc-modified-id="Exercises:-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Exercises:</a></span></li></ul></div>

# 04 Basic Array Operations

In [1]:
import numpy as np

## Array and Scalars

In [3]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [4]:
a + 1

array([1, 2, 3, 4])

In [5]:
a * 2

array([0, 2, 4, 6])

In [6]:
2 ** a

array([1, 2, 4, 8])

## Array and Arrays

In [7]:
b = np.arange(4, 8)
b

array([4, 5, 6, 7])

In [8]:
a + b

array([ 4,  6,  8, 10])

In [9]:
a - b

array([-4, -4, -4, -4])

In [10]:
a * b  # Careful, elementwise

array([ 0,  5, 12, 21])

In [11]:
a.dot(b)

38

## Multi-Dimensional

In [12]:
a = np.ones((5, 5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [14]:
a * b

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [15]:
a - b

array([[ 1.,  0., -1., -2., -3.],
       [ 1.,  0., -1., -2., -3.],
       [ 1.,  0., -1., -2., -3.],
       [ 1.,  0., -1., -2., -3.],
       [ 1.,  0., -1., -2., -3.]])

In [16]:
b - a

array([[-1.,  0.,  1.,  2.,  3.],
       [-1.,  0.,  1.,  2.,  3.],
       [-1.,  0.,  1.,  2.,  3.],
       [-1.,  0.,  1.,  2.,  3.],
       [-1.,  0.,  1.,  2.,  3.]])

#### even NumPy can't do wonders 

In [18]:
c = np.arange(6)


In [20]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
c

array([0, 1, 2, 3, 4, 5])

In [23]:
a - c[:5]

array([[ 1.,  0., -1., -2., -3.],
       [ 1.,  0., -1., -2., -3.],
       [ 1.,  0., -1., -2., -3.],
       [ 1.,  0., -1., -2., -3.],
       [ 1.,  0., -1., -2., -3.]])

## Mathematical Funtions

In [24]:
a = np.linspace(0, 2 * np.pi, 100)
a

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [25]:
np.sin(a)

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [27]:

plt.plot(a, np.sin(a));

NameError: name 'plt' is not defined

In [ ]:
# cos, tan, arcos [...]

In [ ]:
np.exp(a)

In [ ]:
plot(np.exp(a))

## Universal Functions

In [ ]:
a = np.arange(600)
np.mean(a)

In [ ]:
a.mean()

In [ ]:
a.sum()

In [ ]:
%timeit a.sum()

In [ ]:
%timeit sum(a)  # might use NumPys sum when using pylab

In [ ]:
b = np.arange(5 * 20).reshape(5, 20)

In [ ]:
b.sum()

In [ ]:
b[:, 0].sum()

Most of these functions can be applied along one axis

In [ ]:
b.sum(axis=0)

In [ ]:
b.sum(axis=1)

In [ ]:
b.mean(axis=1)

# More Examples

In [ ]:
b = np.random.uniform(0, 1, 5*20).reshape(5, 20)
np.median(b)   # there is no array.median()

In [ ]:
np.median(b, axis=1)

In [ ]:
np.max(b)

In [ ]:
np.min(b)

In [ ]:
np.argmax(b)  # The Maximum's index

In [ ]:
np.argmin(b)

## Transpose

In [ ]:
a = np.arange(1,26).reshape(5, 5)
a

In [ ]:
a.transpose()

In [ ]:
a.T  # for lazy people

## Test for Array properties

In [ ]:
a

Test if at least one element fulfills a requirement

In [ ]:
b = a > 20
b.any()  # any() ist True, wenn min. ein Element True ist

In [ ]:
b

In [ ]:
np.any(a == 0)  # easier still

Testing if all elements fulfill a requirement

In [ ]:
np.all(a > 0)

In [ ]:
np.all(a % 2 == 0)

### Test on Equality

In [ ]:
a = np.arange(6)
b = a.copy()
c = np.arange(6).reshape(2, 3)

In [ ]:
np.array_equal(a, b)  # Tests on shape and content

In [ ]:
np.array_equal(a, c)  

In [ ]:
a = [1, 2]
b = [[1, 2], [1, 2]]
c = [[1, 2, 1, 2], [1, 2, 1, 2]]

In [ ]:
np.array_equiv(a, b)  # Tests on broadcastable shape and same content

In [ ]:
np.array_equiv(a, c)

Testing if two arrays are nearly equal *np.allclose(a, b)*

In [ ]:
a = [1, 2]
b = [1.00001, 2]
c = [1.0001, 2]

In [ ]:
np.allclose(a, b)

In [ ]:
np.allclose(a, c)

In [ ]:
np.allclose(a, b, atol=1e-10)  # setting relative tolerance (default is 1e-5)

In [ ]:
# always False for np.nan 

In [ ]:
np.allclose([1.0, np.nan], [1.0, np.nan])

# Exercises:

<div class="alert alert-success">
<li>subtract its mean from a 5 x 5 array (values from 0 - 24 )</li>
<li>normalize the array's sum to 1 (and test for it)</li>
<li>normalize a random array to mean 0 (values from 0 to 1)</li>
<li>sort a random array ascending and descending (np.sort)</li>
<li>mirror the lower triangle of a 10 x 10 array (values from 1 - 100) to the upper triangle (np.triu(), np.tril(), np.dialognal())</li>
</div>

In [ ]:
a = np.arange(0., 25.).reshape(5, 5)
a - a.mean()

In [ ]:
b = a/a.sum()
b.sum()

In [ ]:
a = np.random.random((10, 10))
a = (a - a.min())/(a.max() - a.min())
a

In [ ]:
a = np.random.random(10)
a.sort()
a

In [ ]:
a[::-1]

In [ ]:
a = np.arange(1, 101).reshape(10, 10)
lower = np.tril(a, -1)                                         
sym = lower.T + lower + np.diagonal(a) * np.identity(10)
print(a)
print(lower)
print(sym)

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.imshow(a)

In [ ]:
plt.imshow(sym)