 # Table of Contents
<div class="toc" style="margin-top: 1em;"><ul class="toc-item" id="toc-level0"><li><span><a href="http://localhost:8888/notebooks/numpy-tutorial_en/A01_Views_and_Copies.ipynb#A01-Views-and-Copies" data-toc-modified-id="A01-Views-and-Copies-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>A01 Views and Copies</a></span><ul class="toc-item"><li><span><a href="http://localhost:8888/notebooks/numpy-tutorial_en/A01_Views_and_Copies.ipynb#Views" data-toc-modified-id="Views-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Views</a></span></li><li><span><a href="http://localhost:8888/notebooks/numpy-tutorial_en/A01_Views_and_Copies.ipynb#changing-the-datatype-with-view()" data-toc-modified-id="changing-the-datatype-with-view()-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>changing the datatype with view()</a></span></li><li><span><a href="http://localhost:8888/notebooks/numpy-tutorial_en/A01_Views_and_Copies.ipynb#Copies" data-toc-modified-id="Copies-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Copies</a></span></li><li><span><a href="http://localhost:8888/notebooks/numpy-tutorial_en/A01_Views_and_Copies.ipynb#Reshaping" data-toc-modified-id="Reshaping-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Reshaping</a></span></li></ul></li></ul></div>

In [2]:
import numpy as np

# A01 Views and Copies

In [3]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [4]:
b = a

In [6]:
a is b  # no data is copied, a is the same object as b

True

In [7]:
b[0] = 99  # data in b is changed => data in a is changed as well
a

array([99,  1,  2,  3,  4,  5])

In [9]:
b.shape = 2, 3  # if the shape of b is changed, a's shape is changed as well (also valid for all other attributes)
a

array([[99,  1,  2],
       [ 3,  4,  5]])

No data is copied on a function call (same as for all other mutable objects in pyhon)

In [10]:
def foo(x):
    x[-1,-1] = 99
foo(a)
a

array([[99,  1,  2],
       [ 3,  4, 99]])

## Views

In [11]:
a = np.arange(6)
c = a[:]


In [12]:
c is a  # c is a "View" on a's data (in this case, all of a's data)

False

In [13]:
print(id(c))   # the header is placed at different locations in memory
print(id(a))

139757096646496
139757096647456


In [14]:
c[2] = 99  # same as before, if data is changed in c, a's data is changed as well

In [15]:
a

array([ 0,  1, 99,  3,  4,  5])

In [19]:
a = np.arange(10.)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [20]:
b = a[:6]  # view on only a fraction of a's data
b

array([ 0.,  1.,  2.,  3.,  4.,  5.])

In [21]:
b.shape = (2, 3)
b

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.]])

In [ ]:
a  # if only the b's header is chaned, a stays the same as before

In [22]:
b[1,0] = 99
b

array([[  0.,   1.,   2.],
       [ 99.,   4.,   5.]])

In [23]:
a  # still, if data is changed in b, it can be see nin a as well

array([  0.,   1.,   2.,  99.,   4.,   5.,   6.,   7.,   8.,   9.])

In [26]:
np.may_share_memory(a, b)  # tests if a and b *may* share memory

True

In [29]:
a.dtype

dtype('float64')

## changing the datatype with view()

In [31]:
b = a.view(dtype=np.int8)  # creates a view with dtype=int8

In [30]:
b[1] = 2   # ATTENTION: we write an int8, but in a it is interpreted as a float
a

array([  2.52961611e-321,   1.00000000e+000,   2.00000000e+000,
         9.90000000e+001,   4.00000000e+000,   5.00000000e+000,
         6.00000000e+000,   7.00000000e+000,   8.00000000e+000,
         9.00000000e+000])

## Copies

In [32]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [33]:
b = np.copy(a)  # we intentionally create a copy of a

In [34]:
a is b

False

In [35]:
a[0] = 99
b

array([0, 1, 2, 3, 4, 5])

In [36]:
np.may_share_memory(a, b)

False

## Reshaping

Reshping may return a view or a copy

In [38]:
a = np.zeros((6, 4))
a

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [39]:
b = a.T

In [40]:
c = b.reshape(24)

In [41]:
np.may_share_memory(a, c)  # c is a copy of a/b

False

In [46]:
b.shape = 24  # can't set the shape

AttributeError: incompatible shape for a non-contiguous array

In [47]:
b.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [42]:
a.strides

(32, 8)

In [43]:
b.strides

(8, 32)

In [44]:
c.strides

(8,)

In [48]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [49]:
b.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [50]:
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [ ]:
d = np.ones((4, 6), order='F')

In [ ]:
d.flags

In [ ]:
d.strides

In [ ]:
c[0:0] = 99

In [ ]:
a

In [ ]:
b

In [ ]:
b.setflags(uic=True)